# Settings for local testing
server.port: 8084

spring:
  application:
    name: Fulltext API
  data:
    mongodb: REMOVED
      uri:
      database: fulltext
      repositories:
        type: auto
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:localhost;DB_CLOSE_ON_EXIT=FALSE
    username: admin
    password: